-- Generated by zshell. Lualine theme matching the zshell colorscheme.

local is_light = "dark" == "light"
local function pick(light, dark)
  return is_light and light or dark
end

local c = {
  bg = "#1A1206",
  bg_alt = "#231A0D",
  bg_mid = pick("#32291A", "#271E11"),
  fg = "#F1E0CA",
  fg_muted = "#DBC3A1",
  fg_strong = pick("#15161A", "#F4F4F8"),

  normal = "#7D2C1E",
  insert = "#733429",
  visual = "#B5893E",
  replace = "#93000A",
  command = pick("#FFDFD5", "#B9AB66"),
  inactive = "#231A0D",

  normal_fg = pick("#15161A", "#F4F4F8"),
  insert_fg = pick("#15161A", "#F4F4F8"),
  visual_fg = pick("#15161A", "#F4F4F8"),
  replace_fg = pick("#15161A", "#F4F4F8"),
  command_fg = pick("#15161A", "#F4F4F8"),
}

return {
  normal = {
    a = { fg = c.normal_fg, bg = c.normal, gui = "bold" },
    b = { fg = c.fg_strong, bg = c.bg_mid },
    c = { fg = c.fg, bg = c.bg_alt },
  },
  insert = {
    a = { fg = c.insert_fg, bg = c.insert, gui = "bold" },
    b = { fg = c.fg_strong, bg = c.bg_mid },
    c = { fg = c.fg, bg = c.bg_alt },
  },
  visual = {
    a = { fg = c.visual_fg, bg = c.visual, gui = "bold" },
    b = { fg = c.fg_strong, bg = c.bg_mid },
    c = { fg = c.fg, bg = c.bg_alt },
  },
  replace = {
    a = { fg = c.replace_fg, bg = c.replace, gui = "bold" },
    b = { fg = c.fg_strong, bg = c.bg_mid },
    c = { fg = c.fg, bg = c.bg_alt },
  },
  command = {
    a = { fg = c.command_fg, bg = c.command, gui = "bold" },
    b = { fg = c.fg_strong, bg = c.bg_mid },
    c = { fg = c.fg, bg = c.bg_alt },
  },
  inactive = {
    a = { fg = c.fg_muted, bg = c.inactive, gui = "bold" },
    b = { fg = c.fg_muted, bg = c.inactive },
    c = { fg = c.fg_muted, bg = c.bg },
  },
}
