-- Generated by zshell. Lualine theme matching the zshell colorscheme.

local is_light = "dark" == "light"
local function pick(light, dark)
  return is_light and light or dark
end

local c = {
  bg = "#161219",
  bg_alt = "#1E1A21",
  bg_mid = pick("#2D2830", "#221E25"),
  fg = "#E9E0EA",
  fg_muted = "#CEC3D3",
  fg_strong = pick("#15161A", "#F4F4F8"),

  normal = "#894FBF",
  insert = "#543D68",
  visual = "#B2417A",
  replace = "#93000A",
  command = pick("#FFDCF2", "#A9A5D8"),
  inactive = "#1E1A21",

  normal_fg = pick("#15161A", "#F4F4F8"),
  insert_fg = pick("#15161A", "#F4F4F8"),
  visual_fg = pick("#15161A", "#F4F4F8"),
  replace_fg = pick("#15161A", "#F4F4F8"),
  command_fg = pick("#15161A", "#F4F4F8"),
}

return {
  normal = {
    a = { fg = c.normal_fg, bg = c.normal, gui = "bold" },
    b = { fg = c.fg_strong, bg = c.bg_mid },
    c = { fg = c.fg, bg = c.bg_alt },
  },
  insert = {
    a = { fg = c.insert_fg, bg = c.insert, gui = "bold" },
    b = { fg = c.fg_strong, bg = c.bg_mid },
    c = { fg = c.fg, bg = c.bg_alt },
  },
  visual = {
    a = { fg = c.visual_fg, bg = c.visual, gui = "bold" },
    b = { fg = c.fg_strong, bg = c.bg_mid },
    c = { fg = c.fg, bg = c.bg_alt },
  },
  replace = {
    a = { fg = c.replace_fg, bg = c.replace, gui = "bold" },
    b = { fg = c.fg_strong, bg = c.bg_mid },
    c = { fg = c.fg, bg = c.bg_alt },
  },
  command = {
    a = { fg = c.command_fg, bg = c.command, gui = "bold" },
    b = { fg = c.fg_strong, bg = c.bg_mid },
    c = { fg = c.fg, bg = c.bg_alt },
  },
  inactive = {
    a = { fg = c.fg_muted, bg = c.inactive, gui = "bold" },
    b = { fg = c.fg_muted, bg = c.inactive },
    c = { fg = c.fg_muted, bg = c.bg },
  },
}
