require("barbar").setup ({
    animation = true,
    auto_hide = false,
    tabpages = true,
    clickable = true,
    exclude_ft = { "NvimTree" },
    focus_on_close = 'left',
    highlight_alternate = false,
    highlight_inactive_file_icons = true,
    highlight_visible = true,
    icons = {
        buffer_index = false,
        buffer_number = false,
        button = '',
        diagnostics = {
            [vim.diagnostic.severity.ERROR] = {enabled = true, icon = 'ﬀ'},
            [vim.diagnostic.severity.WARN] = {enabled = false},
            [vim.diagnostic.severity.INFO] = {enabled = false},
            [vim.diagnostic.severity.HINT] = {enabled = true},
        },
        gitsigns = {
            added = {enabled = true, icon = '+'},
            changed = {enabled = true, icon = '~'},
            deleted = {enabled = true, icon = '-'},
        },
        filetype = {
            custom_colors = false,
            enabled = true,
        },
        separator = {left = '▏', right = ''},
        separator_at_end = true,
        modified = {button = '●'},
        pinned = {button = '', filename = true},
        preset = 'default',
        alternate = {filetype = {enabled = true}},
        current = {buffer_index = false},
        inactive = {button = '×', filetype = {enabled = true}, separator = {left = '▏', right = ''} },
        visible = {modified = {buffer_number = false}},
    },
    insert_at_end = true,
    maximum_padding = 1,
    minimum_padding = 1,
    maximum_length = 15,
    minimum_length = 15,
    sidebar_filetypes = {
        NvimTree = true,
        undotree = {
            text = "undotree",
            align = "center",
        },
    },
})
